// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package signon

import (
	"database/sql"
)

type Signon struct {
	ID                   int64
	IDPc                 int64
	CreatedAt            string
	EnergyType           sql.NullString
	Company              sql.NullString
	Firstname            sql.NullString
	Lastname             sql.NullString
	Zip                  sql.NullString
	City                 sql.NullString
	Street               sql.NullString
	HouseNo              sql.NullString
	PcState              sql.NullString
	DesiredDeliveryStart sql.NullString
	MeterNo              sql.NullString
	Malo                 sql.NullString
	Melo                 sql.NullString
	ConfigID             sql.NullString
}

type SignonContext struct {
	SignonIDPc int64
	State      string
	Comment    string
}
